### ISSUE TITLE
♻️ 트랜잭션 단위 atomic하게 설정하기

### ISSUE THREAD

**Issue by yooooonshine** [IT-Cotato/9th-Midpoint-BE#88]
## Description
- 현재 market api는 중간에 에러가 났을 때 롤백에 되고 있지 않다.
- 이 외에도 여러 로직을 처리하는 api들이 롤백이 되지 않는다.
## Todo
- 모든 트랜잭션 단위의 로직들이 atomic하게 동작하도록 설정한다.

**Comment by shinyj0** [comment]
확인했습니다👍🏻
